name: RSS provider

on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

permissions:
  contents: read
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v3

    - name: Demo cache
      uses: actions/cache@v3
      with:
        key: deno
        path: |
          ~/.deno
          ~/.cache/deno

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Load cache database
      uses: actions/cache@v3
      with:
        key: cache-rss
        path: cache.sqlite

    - name: Run Deno
      env: ${{ secrets }}
      run: deno run --allow-all rss/provider.ts

    - name: Remove cache
      if: always()
      continue-on-error: true
      run: |
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/caches?key=cache-rss

    - name: Save cache
      uses: actions/cache@v3
      with:
        key: cache-rss
        path: cache.sqlite
